site_name: My Docs
site_url: https://gabriel-brody.github.io/pages/
#repo_url: https://github.com/gabriel-brody/pages

theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
    
  features:
    - navigation.instant
    - navigation.tracking

extra_css:
 - stylesheets/extra.css

plugins:
  - search


markdown_extensions: 
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - toc:
      permalink: true
      separator: "-"
  - pymdownx.highlight
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.magiclink


nav:
  - Home: index.md
  - About: about.md
  - My Page: my_page.md