site_name: My Docs
site_url: https://gabriel-brody.github.io/pages/

theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
    
  features:
    - navigation.instant
    - navigation.tracking

extra_css:
 - stylesheets/extra.css

plugins:
  - search


nav:
  - Home: index.md
  - About: about.md