site_name: Lista de Prestadores

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
  - Lista Completa: all.md
  - Advogado: advogado.md
  - Alimentos: alimentos.md
  - Aquecedor: aquecedor.md
  - Ar Condicionado: ar_condicionado.md
  - Arquiteto: arquiteto.md
  - Aspirador de Pó: aspiradort.md
  - Assistência Técnica: assist_tecnica.md
  - Áudio: audio.md
  - Auto Escola: auto_escola.md
  - Barbearia: barbearia.md
  - Bebidas: bebidas.md
  - Buffet: buffet.md
  - Calhas: calhas.md
  - Churrasco: churrasco.md
  - Construtor: construtor.md
  - Corretor de Imóveis: corretor_imoveis.md
  - Cortinas: cortinas.md
  - Engenheiro Calculista: eng_calculista.md
  - Stogare: storage.md
  - Costureira: costureira.md
  - Cuidador: cuidador.md
  - Detetização: detetizacao.md
  - Dentista: dentista.md
  - Desentupidora: desentupidora.md
  - Despachante: despachante.md
  - Diarista: diarista.md
  - Doação: doacao.md
  

theme: material
