site_name: Lista de Prestadores

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins: []

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js


nav:
  - Advogado: advogado.md
  - Alimentos: alimentos.md
  - Aquecedor: aquecedor.md
  - Ar Condicionado: ar_condicionado.md
  - Sem Formatação: all.md

theme: material